name: docs

on:
  # 每当 push 到 main 分支时触发部署
  # push:
  #   branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      # 检出仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
          # 如果你文档需要Git 子模块(submodule)，请取消下一行的注释
          # submodules: true
      
      # 缓存 yarn
      - name: Setup Yarn
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
          cache: yarn
      
      # 安装依赖
      - name: Install
        run: yarn install

      # 更新依赖
      - run: yarn upgrade
        
      # 运行构建脚本
      - name: Build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn run docs:build
        

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
